# GitHub funding links for the repository Sponsor button.
# Replace placeholder handles/URLs with your real accounts.

github: [YOUR_GITHUB_USERNAME]
buy_me_a_coffee: YOUR_BUYMEACOFFEE_HANDLE
ko_fi: YOUR_KOFI_HANDLE
custom: ["https://paypal.me/YOUR_PAYPAL_HANDLE"]
